---
on:
  push:
    branches:
      - main

name: release

jobs:
  release-please:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      packages: write
      issues: write

    steps:
      - uses: googleapis/release-please-action@v4
        name: release
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: ${{ github.repository }}
